case 1:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
break;
case 2:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
break;
case 3:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
break;
case 4:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
break;
case 5:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
break;
case 6:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){6,y,z};
break;
case 7:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){7,y,z};
break;
case 8:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){8,y,z};
break;
case 9:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){9,y,z};
break;
case 10:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){10,y,z};
break;
case 11:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-11,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){11,y,z};
break;
case 12:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-12,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-11,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){11,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){12,y,z};
break;
case 13:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-13,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-12,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-11,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){11,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){12,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){13,y,z};
break;
case 14:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-14,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-13,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-12,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-11,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){11,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){12,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){13,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){14,y,z};
break;
case 15:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-15,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-14,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-13,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-12,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-11,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){11,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){12,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){13,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){14,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){15,y,z};
break;
case 16:
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-16,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-15,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-14,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-13,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-12,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-11,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){-1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){0,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){1,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){2,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){3,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){4,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){5,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){6,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){7,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){8,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){9,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){10,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){11,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){12,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){13,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){14,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){15,y,z};
  xxx++;
  if (seg.nil16(xxx,yyy,zzz)) n += (ivec3){16,y,z};
break;
