SHARED = lib.dylib

all: $(SHARED) runtests ntest

clean:
	rm -f lib.o $(SHARED) runtests
	rm -rf runtests.dSYM

lib.o: lib.c
	gcc  -g -Wall -DCINVOKE_BUILD -DARCH_GCC_X64_OSX -dynamic -c lib.c -o lib.o

$(SHARED): lib.o
	libtool -dynamic -lc -o $(SHARED) lib.o

runtests: runtests.c $(SHARED) ../lib/libcinvoke.a
	gcc -g -Wall -DCINVOKE_BUILD -DARCH_GCC_X64_OSX -o runtests runtests.c -L../lib -I../lib -ldl -lcinvoke -lm

ntest: ntest.c ../lib/libcinvoke.a
	gcc -Wall -DCINVOKE_BUILD -DARCH_GCC_X64_OSX -o ntest ntest.c -L../lib -I../lib -lcinvoke
